version: '3.4'

services:

  mysql-container:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root
    ports:
      - "8080:8080"
    volumes:
      - "$PWD/mysql-entrypoint/:/docker-entrypoint-initdb.d/"
    networks:
      - website-mysql

networks:
  website-mysql: